name: Create Production Builds

on:
  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_to_testflight:
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
